/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface JournalPost {
  'id' : string,
  'title' : string,
  'imageUrl' : string,
  'excerpt' : string,
}
export interface Product {
  'id' : string,
  'name' : string,
  'description' : string,
  'imageUrl' : string,
  'isBestseller' : boolean,
  'category' : ProductCategory,
  'price' : number,
}
export type ProductCategory = { 'collections' : null } |
  { 'skincare' : null } |
  { 'makeup' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addJournalPost' : ActorMethod<[JournalPost], JournalPost>,
  'addProduct' : ActorMethod<[Product], Product>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteJournalPost' : ActorMethod<[string], boolean>,
  'deleteProduct' : ActorMethod<[string], boolean>,
  'getAllProductsByCategory' : ActorMethod<[], Array<[string, Array<Product>]>>,
  'getBestsellers' : ActorMethod<[], Array<Product>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getJournalPosts' : ActorMethod<[], Array<JournalPost>>,
  'getNewsletterSubscribers' : ActorMethod<[], Array<string>>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getProductsByCategory' : ActorMethod<[ProductCategory], Array<Product>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'subscribeNewsletter' : ActorMethod<[string], boolean>,
  'updateJournalPost' : ActorMethod<[string, JournalPost], boolean>,
  'updateProduct' : ActorMethod<[string, Product], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];